services:
  frontend:
    build:
      context: .            
      dockerfile: Dockerfile
    container_name: robotics_lab_system_frontend
    ports:
      - "5173:5173"       
    restart: unless-stopped
